version: '4.4.5.{build}'

pull_requests:
  do_not_increment_build_number: true

environment:
  snk_secret:
    secure: PS4Bb+EzT83oeKqzwgwSr+n116gWIz2MzxDRgHp6Pl1Zx4kEWP0yLpv/ops4WOV1

branches:
  only:
  - master

image: Visual Studio 2019
configuration: Release

install:
  - if defined snk_secret (nuget install secure-file -ExcludeVersion)
  - if defined snk_secret (secure-file\tools\secure-file -decrypt Source\IronMeta.Library\IronMeta.snk.enc -secret %snk_secret%)
  - if not defined snk_secret (copy Source\IronMeta.Library\IronMeta.PRS.snk Source\IronMeta.Library\IronMeta.snk)

before_build:
- nuget restore

build:
  verbosity: minimal

after_build:
- dotnet pack Source\IronMeta.Library\IronMeta.Library.csproj -c %CONFIGURATION%

test:
  assemblies:
    only:
      - IronMeta.Tests.dll

test_script:
- dotnet test "%APPVEYOR_BUILD_FOLDER%\Source\IronMeta.Tests\IronMeta.Tests.csproj" --configuration Release --no-build --logger AppVeyor

artifacts:
- path: '**\IronMeta.*.nupkg'

deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: Nkvb4OfARXcriqmGGzoEiIDTmz8IUdT4ONkZpm/9+qWhnmFo9JS65/QrwkE/iW6N
  skip_symbols: false
  artifact: /.*\.nupkg/
