name: Build and Test
on:
  push:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: windows-2019
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore IronMeta.sln
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal
